export const LOAD_CATEGORY_PRODUCT = 'ustraa/Home/LOAD_CATEGORY_PRODUCT';
export const LOAD_CATEGORY_PRODUCT_SUCCESS = 'ustraa/Home/LOAD_CATEGORY_PRODUCT_SUCCESS';
export const LOAD_CATEGORY_PRODUCT_ERROR = 'ustraa/Home/LOAD_CATEGORY_PRODUCT_ERROR';
